version: '3.9'
services:
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - '6382:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--save', '20', '1', '--loglevel', 'warning']

volumes:
  redis_data:
