version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - '6382:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--save', '20', '1', '--loglevel', 'warning']
    networks:
      - elk
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - '9200:9200'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9200 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elk

  kibana: # http://localhost:5601/
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - '5601:5601'
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk

volumes:
  redis_data:

networks:
  elk:
    driver: bridge
